---

- name: Refresh apt cache
  apt:
    update_cache: yes
  sudo: yes

- name: Install tmux
  apt:
    name: tmux
  sudo: yes

- name: Set tmux config file
  copy:
    src: tmux.conf
    dest: /etc/tmux.conf
  sudo: yes

